name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git user identity
        run: |
          git config --global user.email "albertmanjon123@gmail.com"
          git config --global user.name "Albert Manjón"


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11'

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run storybook-build

      - name: List build directory
        run: ls ./dist/storybook/lib-ui

      - name: Create or update gh-pages branch
        run: |
          git fetch
          # Si la rama gh-pages no existe, crearla
          if ! git show-ref --quiet refs/heads/gh-pages; then
              git checkout --orphan gh-pages
              git rm -rf .  # Eliminar todos los archivos
              git pull origin gh-pages
              git commit --allow-empty -m "Initial commit for gh-pages"
              git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/manjon2000/library-components.git gh-pages
          else
              git fetch origin gh-pages
              git checkout gh-pages
              git pull origin gh-pages
          fi

      - name: Create or update gh-pages branch
        run: |
            # Asegúrate de estar en la rama gh-pages
            git checkout gh-pages
            git rm -rf .
            cp -r ./dist/storybook/lib-ui/* ./
            git add .
            git commit -m "Deploy Storybook to GitHub Pages"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/manjon2000/library-components.git gh-pages
